name: Terraform Infra (AWS)

on:
  push:
    branches: [ main ]
    paths:
      - 'infra/**'
      - '.github/workflows/terraform-infra.yml'

  pull_request:
    branches: [ main ]
    paths:
      - 'infra/**'
      - '.github/workflows/terraform-infra.yml'

  workflow_dispatch:

defaults:
  run:
    working-directory: infra/frontend

concurrency:
  group: terraform-frontend-prod
  cancel-in-progress: false

jobs:
  terraform-plan:
    name: Terraform Plan
    runs-on: ubuntu-latest

    permissions:
      contents: read
      pull-requests: write
      id-token: write   # REQUIRED FOR OIDC

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v3
        with:
          terraform_version: 1.9.6

      # üîê GitHub OIDC ‚Üí AWS IAM Role
      - name: Configure AWS credentials via OIDC
        uses: aws-actions/configure-aws-credentials@v4
        with:
          role-to-assume: arn:aws:iam::242046727288:role/github-actions-terraform
          aws-region: eu-central-1
          role-session-name: github-terraform-plan

      - name: Terraform Init
        run: terraform init -input=false

      - name: Terraform Validate
        run: terraform validate

      - name: Terraform Format Check
        run: terraform fmt -check -recursive

      - name: Terraform Plan
        run: |
          terraform plan \
            -var-file=prod.tfvars \
            -no-color \
            -input=false
